-- rollback: restore old image_url values
START TRANSACTION;
UPDATE products SET image_url = '/Assets/Images/products/macbook_pro.png' WHERE id = 1;
UPDATE products SET image_url = '/Assets/Images/products/monitor_gaming.png' WHERE id = 2;
UPDATE products SET image_url = '/Assets/Images/products/usb_hub.png' WHERE id = 3;
UPDATE products SET image_url = '/Assets/Images/products/usb_hub.png' WHERE id = 4;
UPDATE products SET image_url = '/Assets/Images/products/portable_charger.png' WHERE id = 5;
UPDATE products SET image_url = '/Assets/Images/products/tablet.png' WHERE id = 6;
UPDATE products SET image_url = '/Assets/Images/products/monitor_gaming.png' WHERE id = 7;
UPDATE products SET image_url = '/Assets/Images/products/leather_jacket.png' WHERE id = 8;
UPDATE products SET image_url = '/Assets/Images/products/classic_jeans.png' WHERE id = 9;
UPDATE products SET image_url = '/Assets/Images/products/dress_elegant.png' WHERE id = 10;
UPDATE products SET image_url = '/Assets/Images/products/sneakers_premium.png' WHERE id = 11;
UPDATE products SET image_url = '/Assets/Images/products/scarf_silk.png' WHERE id = 12;
UPDATE products SET image_url = '/Assets/Images/products/running_shoes.png' WHERE id = 13;
UPDATE products SET image_url = '/Assets/Images/products/sunglasses_style.png' WHERE id = 14;
UPDATE products SET image_url = '/Assets/Images/products/designer_watch.png' WHERE id = 15;
UPDATE products SET image_url = '/Assets/Images/products/sunglasses_style.png' WHERE id = 16;
UPDATE products SET image_url = '/Assets/Images/products/scarf_silk.png' WHERE id = 17;
UPDATE products SET image_url = '/Assets/Images/products/design_patterns.png' WHERE id = 18;
UPDATE products SET image_url = '/Assets/Images/products/design_patterns.png' WHERE id = 19;
UPDATE products SET image_url = '/Assets/Images/products/design_patterns.png' WHERE id = 20;
UPDATE products SET image_url = '/Assets/Images/products/clean_code.png' WHERE id = 21;
UPDATE products SET image_url = '/Assets/Images/products/clean_code.png' WHERE id = 22;
UPDATE products SET image_url = '/Assets/Images/products/clean_code.png' WHERE id = 23;
UPDATE products SET image_url = '/Assets/Images/products/web_development.png' WHERE id = 24;
UPDATE products SET image_url = '/Assets/Images/products/design_patterns.png' WHERE id = 25;
UPDATE products SET image_url = '/Assets/Images/products/modern_lamp.png' WHERE id = 26;
UPDATE products SET image_url = '/Assets/Images/products/decorative_mirror.png' WHERE id = 27;
UPDATE products SET image_url = '/Assets/Images/products/designer_chair.png' WHERE id = 28;
UPDATE products SET image_url = '/Assets/Images/products/modern_lamp.png' WHERE id = 29;
UPDATE products SET image_url = '/Assets/Images/products/designer_chair.png' WHERE id = 30;
UPDATE products SET image_url = '/Assets/Images/products/rug.png' WHERE id = 31;
UPDATE products SET image_url = '/Assets/Images/products/gravel_bike.png' WHERE id = 32;
UPDATE products SET image_url = '/Assets/Images/products/yoga_mat.png' WHERE id = 33;
UPDATE products SET image_url = '/Assets/Images/products/running_shoes.png' WHERE id = 34;
UPDATE products SET image_url = '/Assets/Images/products/portable_charger.png' WHERE id = 35;
COMMIT;
